

services:
  
  db:
    image: postgres:15
    container_name: stock_db
    environment:
      POSTGRES_DB: stock_analysis
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  db_test:
    image: postgres:15
    container_name: stock_db_test
    environment:
      POSTGRES_DB: stock_analysis_test
      POSTGRES_USER: stock_user_test
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1
    volumes:
      - cache:/data


  
  app:
    build: 
      context: .
      target: prod
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: stock_analysis
      POSTGRES_USER: stock_user
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_PORT: 5432
      RATE_LIMIT: 10
      RATE_LIMIT_WINDOW: 90
      ALGORITHM: HS256
      FINNHUB_API_KEY: ${FINNHUB_API_KEY}
  test:
    build:
      context: .
      target: test
    depends_on:
      - db_test
      - redis
    environment:
      POSTGRES_HOST: db_test
      POSTGRES_PORT: 5433
      ALGORITHM: HS256
      REDIS_URL: redis://redis:6379/0
      RATE_LIMIT: 10
      RATE_LIMIT_WINDOW: 90
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: stock_analysis_test
      POSTGRES_USER: stock_user_test
      FINNHUB_API_KEY: ${FINNHUB_API_KEY}
volumes:
  cache: