"""message

Revision ID: 743379383587
Revises: 5746511c2d91
Create Date: 2026-01-26 12:56:26.102277

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "743379383587"
down_revision: Union[str, Sequence[str], None] = "5746511c2d91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_prices",
        sa.Column("lower_shadow", sa.Numeric(precision=10, scale=4), nullable=False),
    )
    op.drop_column("daily_prices", "ower_shadow")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_prices",
        sa.Column(
            "ower_shadow",
            sa.NUMERIC(precision=10, scale=4),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("daily_prices", "lower_shadow")
    # ### end Alembic commands ###
