"""message

Revision ID: 864cb3c07f41
Revises: 743379383587
Create Date: 2026-01-27 11:11:50.343780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "864cb3c07f41"
down_revision: Union[str, Sequence[str], None] = "743379383587"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("daily_prices", "adj_close")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_prices",
        sa.Column(
            "adj_close",
            sa.NUMERIC(precision=10, scale=4),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
