"""create table

Revision ID: b1245d5d30cb
Revises:
Create Date: 2026-02-05 11:03:47.259309

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1245d5d30cb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("ticker", sa.VARCHAR(length=10), nullable=False),
        sa.Column("open", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("daily_return", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("log_return", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column(
            "rolling_volatility", sa.Numeric(precision=10, scale=4), nullable=True
        ),
        sa.Column("moving_average", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("absolute_range", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column(
            "relative_range_on_open", sa.Numeric(precision=10, scale=4), nullable=False
        ),
        sa.Column(
            "relative_range_on_close", sa.Numeric(precision=10, scale=4), nullable=False
        ),
        sa.Column(
            "open_close_range", sa.Numeric(precision=10, scale=4), nullable=False
        ),
        sa.Column("upper_shadow", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("lower_shadow", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker", "date", name="uq_daily_prices_ticker_date"),
    )
    op.create_index(
        op.f("ix_daily_prices_date"), "daily_prices", ["date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_daily_prices_date"), table_name="daily_prices")
    op.drop_table("daily_prices")
    # ### end Alembic commands ###
