name: CI

on:
    push:
        branches: [main]
    pull_request:
jobs:
    test_and_build:
        runs-on: ubuntu-latest
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FINNHUB_API_KEY: ${{secrets.FINNHUB_API_KEY}}
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build containers
              run: docker compose build
            
            - name: Run tests container
              run: docker compose run --rm test
            
            - name: Stop containers
              run: docker compose down


